# Generated by Django 4.0.3 on 2022-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('email_ID', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('offer', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='slide01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl1', models.CharField(max_length=10)),
                ('ttl2', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='slide01/pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='slide02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl1', models.CharField(max_length=10)),
                ('ttl2', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='slide02/pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
